[workspace]
authors = ["Stuart Berg <bergs@janelia.hhmi.org>"]
channels = ["flyem-forge", "conda-forge"]
name = "env"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
flyem-snapshot = ">=0.1.15.post0.dev122,<0.2"
vol2mesh = ">=0.2,<0.3"
neuclease = ">=0.81.post0.dev31,<0.82"

# The derived-updates tool uses the neutu executable via a subprocess.
# We install it to its own environment by listing it in this "feature"
# and then creating an otherwise empty environment that depends on this "feature".
[feature.neutu.dependencies]
neutu-develop = ">=0.9.18"

[environments]
default = []
neutu = {features = ["neutu"], no-default-feature = true}

[activation]
# Note: set-credentials.sh is excluded from the git repo.
# It sets DVID_ADMIN_TOKEN and NEUPRINT_APPLICATION_CREDENTIALS.
scripts = ["set-credentials.sh"]

[tasks.update-fish2-neuprint-annotations]
cmd = [
    # The update-neuprint-annotations command is shipped with the flyem-snapshot package.
    "update-neuprint-annotations",
    
    # In theory there should be no 'soma_position' or 'soma_location' property in DVID/clio,
    # but some users might be tempted to add it, which would cause the 'somaLocation' property
    # to be overwritten in neuprint.
    # To avoid that, we exclude it from the neuprint updates.
    "--exclude-properties=somaLocation",

    "--output-dir=update-neuprint-annotations/logs/$(date +'%Y-%m-%d.%H-%M-%S')",

    # DVID server/branch/instance
    "emdata7.int.janelia.org:8400",
    ":master",
    "segmentation_annotations",
    
    # neuprint server/dataset
    "neuprint-fish2.janelia.org",
    "fish2"
]

[tasks.fish2-derived-updates]
cmd = ["bash", "../bin/derived-updates-bsub.sh", "fish2", "16"]
